export const externalLinks = {
  behgozin: "https://padashfixedincome.com/",
  leasingInternal: "https://leasing.paadaash.ir/",
  pwa: "https://app.paadaash.ir",
  petroPadash: "http://padashsectorfund.com/",
  pada: "http://www.padashparsfund.com/",
  advise: "https://www.padash.ir/advise",
  sabadPadash: "https://cm.padash.ir/",
  broker: "https://padashbroker.ir/",
  exir: "https://padash.exirbroker.com/",
  ebgo: "https://padash.ebgo.ir/Login",
  about: "/about-us",
  contact: "https://www.padash.ir/advise/contact-us",
  padashregister: "https://padashregister.irbrokersite.ir/",
  academy: "https://academy.padash.ir/",
  fund: "https://fund.paadaash.ir/",
  arzesh: "http://arzeshpadash.com/",
  sahra: "https://mobile.ephoenix.ir/auth/login",
};
